config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :comments
  end
  resources :users, only: [:show]
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    default_scope { order(created_at: :desc) }
    has_many :comments, dependent: :destroy
    validates :user_id, presence: true
    validates :image, presence: true
    belongs_to :user

    has_attached_file :image, styles: { :medium => "640x" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
   

    def create
        @comment = @post.comments.new(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
            respond_to do |format|
                format.html { redirect_to root_path}
                format.js
            end
        else
            flash[:alert] = "Check the comment form"
            render root_path
        end
    end

    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        respond_to do |format|
            format.html { redirect_to root_path }
            format.js
        end
    end

private

    def comment_params
        params.require(:comment).permit(:content)
    end

    def set_post
        @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :owned_post, only: [:edit, :update, :destroy]
    


    def index
        @posts = Post.paginate(page: params[:page], per_page: 2)
    end

    def new
        @post = current_user.posts.new
    end

    def create
        if @post = current_user.posts.create(post_params)
            flash[:success] = "Your post has been created!"
            redirect_to posts_path
        else
            flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @post.update(post_params)
            flash[:success] = "Post updated."
            redirect_to posts_path
        else
            flash.now[:alert] = "Update failed.  Please check the form."
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:image, :caption)
    end

    def owned_post
        unless current_user == @post.user
          flash[:alert] = "That post doesn't belong to you!"
          redirect_to root_path
        end
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params
      params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    

    def show
        @user  = User.find(params[:id])
        @posts = @user.posts.order(created_at: :desc)
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_for(flash_type)
        { success: 'alert-success',
          error: 'alert-danger',
          alert: 'alert-warning',
          notice: 'alert-info'
        }[flash_type.to_sym] || flash_type.to_s
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
  <div class="user-name">
    <%= comment.user.user_name %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="navbar-container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">
                <%= link_to "Photogram", root_path %>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li>
                        <%= link_to "New Post", new_post_path %>
                    </li>
                    <li>
                        <%= link_to "Profile", user_path(current_user) %>
                    </li>
                    <li>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to "Login", new_user_session_path %>
                    </li>
                    <li>
                        <%= link_to "Register", new_user_registration_path %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "manifest" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
      <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
        <% end %>
        <%= yield %>
      </div>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= post.user.user_name %>
          </div>
          <%= post.caption %>
        </div>
        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments %>
            <%= render post.comments, post: post %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>
<%= render 'form' %>
<div class="text-center edit-links">
    <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    |
    <%= link_to "Cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<div id="posts">
  <%= render @posts %>
</div>
</div>
<div id="infinite-scrolling">
  <%= will_paginate @posts %> 
</div>

app/views/posts/index.js.erb
$('#posts').append('<%= j render @posts %>');
    <% if @posts.next_page %>
       $('.pagination').replaceWith('<%= j will_paginate @posts %>');
    <% else %>
       $(window).off('scroll');
       $('.pagination').remove();
    <% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        Divija Palleti
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
    <% if @post.user.id == current_user.id%>
      <div class="text-center">
        <%= link_to "Cancel", posts_path %>
        |
        <%= link_to "Edit Post", edit_post_path(@post) %>
      </div>
    <% else %>
      <div class="text-center">
        <%= link_to "Cancel", posts_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= current_user.user_name %></h2>
      </div>
      <ul class="posts">
        <li><span> <%= @posts.count %></span></li>
        <li><span>y</span> followers</li>
        <li><span>z</span> following</li>
      </ul>
      <h2 class="name"><%= current_user.email %></h2>
    </div>
  </div>
</div>

<div class="user-tabs">
  <a class="tab active" href="">
    <i class="fa fa-th"></i>
    POSTS
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    IGTV
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    SAVED
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    TAGGED
  </a>
</div>

<% @posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>